- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure /var/www/html directory exists
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Create a test PHP file using template
  template:
    src: index.php.j2
    dest: /var/www/html/index.php
    owner: www-data
    group: www-data
    mode: '0644'

- name: Start and enable Nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Configure Nginx to use PHP-FPM
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Reload Nginx to apply changes
  service:
    name: nginx
    state: reloaded
